web/config/routes.rb
Web::Application.routes.draw do
  

  resources :wines do
    
  end
  
  namespace 'wines' do
    resources :analyze do
      member do
        get 'image'
        get 'detail'
      end
    end
  end
    
    
 

  
  

   match ':controller(/:action(/:id))(.:format)'
end

web/app/models/analyze_result.rb
class AnalyzeResult < ActiveRecord::Base
  attr_accessible :count, :id, :remarks, :wine_id, :word  
  
  def to_s()
    return "#{@attributes.word} #{@attributes.count}"  
  end
end

web/app/models/wine.rb
class Wine < ActiveRecord::Base
  def after_initialize
    @analyze_results_info = AnalyzeResultInfo.new  
  end
  attr_accessible :comments, :id, :price, :wine_name
  attr_accessor :analyze_results_info 
  
end

web/app/controllers/CorrelationAnalyzer.rb
require 'rubygems'
require 'MeCab'
include Math

class CorrelationAnalyzer

  def self.analyze(wine)    
    line = wine.comments
    info = create_analyze_result_info_by_line(wine.wine_id,line)
    return info
  end
   
  def self.create_analyze_result_info(wine_id)
  
    info = AnalyzeResultInfo.new
    rows = AnalyzeResult.find_all_by_wine_id(wine_id)
    mecab = create_mecab()
      
    rows.each do |row|
            
      result = AnalyzeResult.new
      result.wine_id = wine_id
      result.word = row.word
      result.remarks = row.remarks     
      info.add_to_dic(result)
    end      
    return info
  end 
  
  def self.create_analyze_result_info_by_line(wine_id,line)
  
    info = AnalyzeResultInfo.new
    mecab = create_mecab() 
      
    node = mecab.parseToNode(line)    
    begin
      node = node.next
      
      result = AnalyzeResult.new
      result.wine_id = wine_id
      result.word = node.surface
      result.remarks = node.feature     
      result.count = 1;
      info.add_to_dic(result)
    end until node.next.feature.include?("BOS/EOS")   
    
    return info
  end  
  
  def self.create_mecab()
    dir_path ="/usr/local/Cellar/mecab/0.996/lib/mecab/dic/"
    dir_name ="ipadic"
    s = "-d #{dir_path}#{dir_name}"
    mecab =MeCab::Tagger.new(s)
    return mecab
  end
  
  def self.calc_correlation(src_wine,dst_wine)
    
    sum_of_squares = 0.0
    
    src_wine.analyze_results_info.word_dic.each do |word,src_info|
      if dst_wine.analyze_results_info.word_dic.include?(word)
        dst_info = dst_wine.analyze_results_info.word_dic[word]
        
        diff = dst_info.count.to_i - src_info.count.to_i
        sum_of_squares += Math::sqrt(diff ** 2)
        
      end
    
    end
    
    return 1.0/(1 + sum_of_squares)
  end  
  
  def make_gruff(src_wine,dst_wine)
    sum_of_squares = 0.0
    
    src_wine.analyze_results_info.word_dic.each do |word,src_info|
      if dst_wine.analyze_results_info.word_dic.include?(word)
        dst_info = dst_wine.analyze_results_info.word_dic[word]
        
        diff = dst_info.count.to_i - src_info.count.to_i
        sum_of_squares += Math::sqrt(diff ** 2)
        
      end
    
    end
    
    return 1.0/(1 + sum_of_squares)
  end
  
end

class AnalyzeResultInfo
  
  def initialize()
    @word_dic = {}    
  end
  attr_accessor :word_dic
  
  def add_to_dic(result)
    if @word_dic.key?(result.word)
      r = @word_dic[result.word]
      @word_dic[result.word].count = r.count.to_i + 1
    else
      @word_dic.store(result.word,result)    
    end
  end
  
  def write_only_count_over(number)
    @word_dic.each {|word,result|
      if result.count >= number
        puts result.to_s()
      end      
    }
  end 
end



  

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/app/controllers/wines/analyze_controller.rb
require "CorrelationAnalyzer"


class Wines::AnalyzeController < ApplicationController
  
  # GET /wines/analyze/1
  # GET /wines/analyze/1.json
  def show    
    
    @wines = Wine.all
    @wine = Wine.find(params[:id])
        
    @analyze_results = AnalyzeResult.find_all_by_wine_id(params[:id])
    @wine.analyze_results_info = CorrelationAnalyzer::create_analyze_result_info(params[:id])
    
    @wines.each do |wine|
      wine.analyze_results_info = CorrelationAnalyzer::create_analyze_result_info(wine.wine_id)
    end  
    
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wine }
    end
  end
  
  def destroy
    
    respond_to do |format|
      format.html { redirect_to wines_url }
      format.json { head :no_content }
    end
  end
  
  
  # GET /wines/analyze/1/detail
  # GET /wines/analyze/1/detail.json
  def detail    
    
    @src_wine = Wine.find(params[:src_id])        
    @dst_wine = Wine.find(params[:dst_id])         
    
    
    respond_to do |format|
      format.html # dtail.html.erb
      format.json { render json: @wine }
    end    
  end
  
  def image    
    
    @src_wine = Wine.find(params[:src_id])        
    @dst_wine = Wine.find(params[:dst_id])          
    
    @src_wine.analyze_results_info = CorrelationAnalyzer::create_analyze_result_info(@src_wine.wine_id)
    @dst_wine.analyze_results_info = CorrelationAnalyzer::create_analyze_result_info(@dst_wine.wine_id)
    
    g = Gruff::Dot.new 500
    g.title = "My Graph" 

    g.theme_37signals

    #g.data("data1", @src_wine.analyze_results_info.word_dic.values )
    g.data("data2", [7, 8, 7, 10, 8, 9])
    g.data("data3", [1, 2, 3, 5, 9, 8])
    g.data("data4", [9, 9, 8, 9, 10, 9])

    g.labels = {0 => '2010/01', 2 => '2010/03', 4 => '2010/05'}
    
    file_name = "t.jpg"    

    send_data(g.to_blob, :type => 'image/png', :disposition=>'inline', :filename => file_name)
  end
  
  
  
end

web/app/controllers/wines_controller.rb
require File.dirname(__FILE__) + '/CorrelationAnalyzer'


class WinesController < ApplicationController
  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wines }
    end
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    @wine = Wine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wine }
    end
  end

  # GET /wines/new
  # GET /wines/new.json
  def new
    @wine = Wine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wine }
    end
  end

  # GET /wines/1/edit
  def edit
    @wine = Wine.find(params[:id])
    s = ""
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(params[:wine])
    @wines = Wine.all

    respond_to do |format|
      if @wine.save
        save_analyze_result(@wine,@wines)
        
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render json: @wine, status: :created, location: @wine }
      else
        format.html { render action: "new" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wines/1
  # PUT /wines/1.json
  def update
    @wine = Wine.find(params[:id])
    @wines = Wine.all

    respond_to do |format|
      if @wine.update_attributes(params[:wine])
        save_analyze_result(@wine,@wines)
        
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url }
      format.json { head :no_content }
    end
  end
  
  def analyze
    redirect_to :controller => 'analyze_controller' ,:action => 'analyze'  
  end
    
  def save_analyze_result(wine,wines)
    
    info = CorrelationAnalyzer::analyze(wine)
    dic = info.word_dic
    dic.each {|word,result|      
      result.save        
    }
   
  end
  private :save_analyze_result
  
end

web/app/helpers/analyze_helper.rb
module AnalyzeHelper
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/wines/analyze_helper.rb
module Wines::AnalyzeHelper
end

web/app/helpers/wines_helper.rb
module WinesHelper
end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :wine_name %><br />
    <%= f.text_field :wine_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/wines/analyze/detail.html.erb
<h1>Wine Analyze Detail</h1>
<%= image_tag url_for(:action => 'image',:src_id => @src_wine.id,:dst_id => @dst_wine.id) %>
<p>
  <b>Id:</b>
  <%= @src_wine.id %>
</p>

<p>
  <b>Wine name:</b>
  <%= @src_wine.wine_name %>
</p>

<p>
  <b>Comments:</b>
  <%= @src_wine.comments %>
</p>

web/app/views/wines/analyze/show.html.erb
<h1>Wine Analyze</h1>
<%#= image_tag url_for(:action => 'image') %>
<p>
  <b>Id:</b>
  <%= @wine.id %>
</p>

<p>ß
  <b>Wine name:</b>
  <%= @wine.wine_name %>
</p>

<p>
  <b>Comments:</b>
  <%= @wine.comments %>
</p>

<p>
  <b>Analyze Results:</b>
<table>
<% @analyze_results.each do |analyze_result| %>
  <tr>
    <td><%= analyze_result.word %></td>
    <td><%= analyze_result.remarks %></td>
    <td><%= analyze_result.count %></td>      
  </tr>
<% end %>
</table>
</p>

<table>
	
  <tr>
    <th>Id</th>
    <th>Wine name</th>
    <th>Comments</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% @wines.each do |wine| %>
<% 	if wine == @wine then next end %>
  <tr>
    <td><%= wine.id %></td>
    <td><%= wine.wine_name %></td>
    <td><%= wine.comments.slice(0,200) %></td>
    <td><%= wine.price %></td>
    <td><%= CorrelationAnalyzer::calc_correlation(@wine,wine) %></td>
    <td><%= link_to "detail", :controller =>"analyze",:action =>"detail",:src_id => @wine.id,:dst_id => wine.id %></td> 
     
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', wines_path %>

web/app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

web/app/views/wines/index.html.erb
<h1>Listing wines</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Wine name</th>
    <th>Comments</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wines.each do |wine| %>
  <tr>
    <td><%= wine.id %></td>
    <td><%= wine.wine_name %></td>
    <td><%= wine.comments.slice(0,200) %></td>
    <td><%= wine.price %></td>
    <td><%= link_to 'Show', wine %></td>
    <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
    <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Analyze', wines_analyze_path(wine.id) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wine', new_wine_path %>

web/app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

web/app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @wine.id %>
</p>

<p>
  <b>Wine name:</b>
  <%= @wine.wine_name %>
</p>

<p>
  <b>Comments:</b>
  <%= @wine.comments %>
</p>

<p>
  <b>Price:</b>
  <%= @wine.price %>
</p>


<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>